// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID            int64              `json:"id"`
	UserID        string             `json:"userId"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	Completed     bool               `json:"completed"`
	DueDate       pgtype.Timestamptz `json:"dueDate"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	Starred       bool               `json:"starred"`
	ScheduledDate pgtype.Timestamptz `json:"scheduledDate"`
}
