// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	Todo_CreateBlank(ctx context.Context, userID string) (int64, error)
	Todo_DeleteOne(ctx context.Context, arg Todo_DeleteOneParams) error
	Todo_GetMany(ctx context.Context, userID string) ([]Todo_GetManyRow, error)
	Todo_GetOneById(ctx context.Context, arg Todo_GetOneByIdParams) (Todo_GetOneByIdRow, error)
	Todo_UpdateOne(ctx context.Context, arg Todo_UpdateOneParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
