// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const todo_CreateOne = `-- name: Todo_CreateOne :one
INSERT INTO todos (
  user_id,
  title,
  description,
  completed,
  due_date,
  starred,
  scheduled_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, description, completed, due_date, created_at, updated_at, starred, scheduled_date
`

type Todo_CreateOneParams struct {
	UserID        string             `json:"userId"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	Completed     bool               `json:"completed"`
	DueDate       pgtype.Timestamptz `json:"dueDate"`
	Starred       bool               `json:"starred"`
	ScheduledDate pgtype.Timestamptz `json:"scheduledDate"`
}

func (q *Queries) Todo_CreateOne(ctx context.Context, arg Todo_CreateOneParams) (Todo, error) {
	row := q.db.QueryRow(ctx, todo_CreateOne,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
		arg.Starred,
		arg.ScheduledDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.ScheduledDate,
	)
	return i, err
}

const todo_DeleteOne = `-- name: Todo_DeleteOne :exec
DELETE FROM todos
WHERE id = $1
AND user_id = $2
`

type Todo_DeleteOneParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"userId"`
}

func (q *Queries) Todo_DeleteOne(ctx context.Context, arg Todo_DeleteOneParams) error {
	_, err := q.db.Exec(ctx, todo_DeleteOne, arg.ID, arg.UserID)
	return err
}

const todo_GetManyByUserId = `-- name: Todo_GetManyByUserId :many
SELECT
  id,
  user_id,
  title,
  description,
  completed,
  due_date,
  starred,
  scheduled_date,
  created_at,
  updated_at
FROM todos
WHERE user_id = $1
ORDER BY id
`

type Todo_GetManyByUserIdRow struct {
	ID            int64              `json:"id"`
	UserID        string             `json:"userId"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	Completed     bool               `json:"completed"`
	DueDate       pgtype.Timestamptz `json:"dueDate"`
	Starred       bool               `json:"starred"`
	ScheduledDate pgtype.Timestamptz `json:"scheduledDate"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) Todo_GetManyByUserId(ctx context.Context, userID string) ([]Todo_GetManyByUserIdRow, error) {
	rows, err := q.db.Query(ctx, todo_GetManyByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo_GetManyByUserIdRow
	for rows.Next() {
		var i Todo_GetManyByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.DueDate,
			&i.Starred,
			&i.ScheduledDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todo_GetOneById = `-- name: Todo_GetOneById :one
SELECT
  id,
  user_id,
  title,
  description,
  completed,
  due_date,
  starred,
  scheduled_date,
  created_at,
  updated_at
FROM todos
WHERE id = $1
AND user_id = $2
`

type Todo_GetOneByIdParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"userId"`
}

type Todo_GetOneByIdRow struct {
	ID            int64              `json:"id"`
	UserID        string             `json:"userId"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	Completed     bool               `json:"completed"`
	DueDate       pgtype.Timestamptz `json:"dueDate"`
	Starred       bool               `json:"starred"`
	ScheduledDate pgtype.Timestamptz `json:"scheduledDate"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) Todo_GetOneById(ctx context.Context, arg Todo_GetOneByIdParams) (Todo_GetOneByIdRow, error) {
	row := q.db.QueryRow(ctx, todo_GetOneById, arg.ID, arg.UserID)
	var i Todo_GetOneByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.DueDate,
		&i.Starred,
		&i.ScheduledDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const todo_UpdateOne = `-- name: Todo_UpdateOne :one
UPDATE todos
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    completed = COALESCE($3, completed), 
    due_date = COALESCE($4, due_date),
    starred = COALESCE($5, starred), 
    scheduled_date = COALESCE($6, scheduled_date)
WHERE id = $7
AND user_id = $8
RETURNING id, user_id, title, description, completed, due_date, created_at, updated_at, starred, scheduled_date
`

type Todo_UpdateOneParams struct {
	Title         *string            `json:"title"`
	Description   *string            `json:"description"`
	Completed     *bool              `json:"completed"`
	DueDate       pgtype.Timestamptz `json:"dueDate"`
	Starred       *bool              `json:"starred"`
	ScheduledDate pgtype.Timestamptz `json:"scheduledDate"`
	ID            int64              `json:"id"`
	UserID        string             `json:"userId"`
}

func (q *Queries) Todo_UpdateOne(ctx context.Context, arg Todo_UpdateOneParams) (Todo, error) {
	row := q.db.QueryRow(ctx, todo_UpdateOne,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
		arg.Starred,
		arg.ScheduledDate,
		arg.ID,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Starred,
		&i.ScheduledDate,
	)
	return i, err
}
