services:
  db:
    image: postgres:latest
    container_name: "${DB_NAME}_database"
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

  db_migrator:
    container_name: db_migrator
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:bionic

        RUN apt-get update && \
            apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent

        RUN curl -sSL https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
        RUN echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ bionic main" > /etc/apt/sources.list.d/migrate.list
        RUN apt-get update && \
            apt-get install -y migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./api/migrations:/api/migrations"
    command: "migrate -database postgres://${DB_USER}:${DB_PASSWORD}@db:5432/golang_vue_todo_app?sslmode=disable -path /api/migrations up"

  db_seeder:
    container_name: db_seeder
    image: postgres:latest
    volumes:
      - "./api/seeds:/api/seeds"
    depends_on:
      db:
        condition: service_healthy
      db_migrator:
        condition: service_completed_successfully
    command: |-
      /bin/sh -c '
      echo "Running all seed scripts from /api/seeds...";
      find /api/seeds -maxdepth 1 -name "*.sql" -exec /bin/sh -c "psql -f \"{}\" || exit 1" \;
      echo "Database seeding complete.";
      '
    environment:
      # Psql client automatically reads these variables:
      PGHOST: db
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_NAME}

volumes:
  postgres_data:
    driver: local
